### ISSUE TITLE
Hardware components?

### ISSUE THREAD

**Issue by pcarew** [mean00/DSO_STM32Duino#10]
It looks like you have a 3d printed case. Did you construct your own device?
I'm looking for replacement Rotary Encoder and was wondering if you had a source?
Thanks

**Comment by mean00** [comment]
I changed the casing to include a battery ( i designed that https://www.thingiverse.com/thing:3737248 )
You can take ~ any rotary encoder and solder it backward
http://goingbacktoelectronic.blogspot.com/2019/08/dso-150-rotary-encoder-busted-simpler.html
They are pretty standard (IEC something), you can buy them on amazon/aliexpress/ebay/....
The only annoying part is sometimes the shaft is long and you have to cut it a bit

**Comment by pcarew** [comment]
ThanksOn Nov 4, 2022 02:08, mean00 ***@***.***> wrote:
I changed the casing to include a battery ( i designed that https://www.thingiverse.com/thing:3737248 )
You can take ~ any rotary encoder and solder it backward
http://goingbacktoelectronic.blogspot.com/2019/08/dso-150-rotary-encoder-busted-simpler.html
They are pretty standard (IEC something), you can buy them on amazon/aliexpress/ebay/....
The only annoying part is sometimes the shaft is long and you have to cut it a bit
